'use client';

import React from 'react';
import { ForensicIncidentReport } from '@/types';
import { X, Network, ExternalLink } from 'lucide-react';

interface TopologyModalProps {
  incident: ForensicIncidentReport | null;
  onClose: () => void;
}

export const TopologyModal: React.FC<TopologyModalProps> = ({
  incident,
  onClose
}) => {
  if (!incident) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 backdrop-blur-sm p-4 font-sans select-text">
      <div className="w-full max-w-3xl bg-[#0a0a0a] border border-[#222222] rounded-2xl shadow-2xl overflow-hidden animate-in fade-in zoom-in-95 duration-150 flex flex-col max-h-[90vh]">
        {/* Header */}
        <div className="p-4 border-b border-[#1a1a1a] flex items-center justify-between">
          <div className="flex items-center gap-2">
            <Network className="w-4 h-4 text-sky-400" />
            <h3 className="font-semibold text-white text-sm">
              Topological Blast-Radius Map &bull; Incident #{incident.mandate_id}
            </h3>
          </div>
          <button
            onClick={onClose}
            className="p-1 text-zinc-500 hover:text-white rounded-md transition"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* Content */}
        <div className="p-5 space-y-4 flex-1 overflow-y-auto">
          {incident.diagram_svg ? (
            <div
              className="w-full bg-[#050505] border border-[#171717] rounded-xl p-4 flex items-center justify-center overflow-x-auto"
              dangerouslySetInnerHTML={{ __html: incident.diagram_svg }}
            />
          ) : (
            <div className="w-full h-48 bg-[#050505] border border-[#171717] rounded-xl flex items-center justify-center text-zinc-500 text-xs font-mono">
              Topological SVG diagram generated by Imagen 3 Scribe
            </div>
          )}

          <div className="p-4 bg-[#050505] border border-[#171717] rounded-xl space-y-2 text-xs">
            <div className="font-semibold text-white">Gemini 3.5 Causal Postmortem Summary:</div>
            <p className="text-zinc-300 leading-relaxed">{incident.root_cause_explanation}</p>
            <div className="pt-2 text-zinc-400 font-mono text-[11px]">
              <strong>Blast Radius: </strong>
              <span className="text-rose-400 font-bold">{incident.risk_score}/100</span>
              <span className="ml-4">
                <strong>Attempted Spend: </strong>
                <span className="text-white">${incident.attempted_amount_usdc} USDC</span>
              </span>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
